# Generated by Django 3.2.23 on 2025-12-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='hobbies',
            field=models.CharField(choices=[('SINGING', 'singing'), ('DRAWING', 'drawing'), ('PHOTOGRAPHY', 'photography'), ('GAMING', 'Gaming'), ('PROGRAMMING', 'programming'), ('VLOGGING', 'vlogging'), ('READING', 'reading'), ('COOKING', 'cooking'), ('DANCING', 'dancing'), ('TRAVELING', 'traveling'), ('LISTENING TO MUSIC', 'listening to music')], default=' SINGING', max_length=300),
        ),
    ]
