# Generated by Django 3.2.23 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_preference_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='hobbies',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
